apiVersion: v1
kind: Secret
metadata:
  name: secret-s3
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
stringData:
  credentials: |
    [default]
    aws_access_key_id = {{ .Values.s3.accessKeyId }}
    aws_secret_access_key = {{ .Values.s3.secretAccessKey }}
    aws_session_token = {{ .Values.s3.sessionToken }}

    [other]
    aws_access_key_id = other
    aws_secret_access_key = other_secret_key:wq
    