apiVersion: v1
kind: Secret
metadata:
  name: secret-mc
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
stringData:
    MC_HOST_s3 : {{ printf "https://%s:%s:%s@%s" .Values.s3.accessKeyId .Values.s3.secretAccessKey .Values.s3.sessionToken .Values.s3.endpoint }}
    MC_HOST_other : "https://<Access Key>:<Secret Key>:<Session Token>@<YOUR-S3-ENDPOINT>"
