repos:
- repo: https://github.com/Gaspi/pre-commit-hooks
  rev: v0.0
  hooks:
  # Validate schemas using the jsonschema.validators package
  - id: validate-json-schemas
    args:
      # Forbid legacy https://json-schema.org/draft/2020-12/schema schema validator and suggest Draft 7 instead
      - --forbid-legacy
  # Ensure technically facultative attribute (such as `type`) are systematically specified
  - id: missing-attributes-schemas
    args:
      # Also require `items` to be systematically specified for arrays
      - --check-items
      # Also require `properties` to be systematically specified for object
      - --check-properties
