{{- if .Values.elasticsearch.discoverable.allow }}
{{- $fullname := include "library-chart.fullname" . }}
{{- $serviceName:= printf "%s-%s" .Release.Name "elasticsearch" }}
{{- $secretName := printf "%s-%s" "discoverable" $fullname -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    onyxia/discovery: "elastic"
type: Opaque
data:
  elastic-service: {{ printf "%s" $serviceName | b64enc | quote }}
  elastic-port: {{ printf "%g" .Values.elasticsearch.service.ports.restAPI | b64enc | quote }}
  elastic-name: {{ printf "%s" $fullname  | b64enc | quote }}
  elastic-password: {{ .Values.elasticsearch.security.elasticPassword | b64enc | quote}}
{{- end -}}