service:
  image:
    pullPolicy: IfNotPresent
    version: inseefrlab/onyxia-vscode-python:py3.12.9
    custom:
      enabled: false
      version: inseefrlab/onyxia-vscode-python:py3.12.9
resources:
  requests:
    cpu: 100m
    memory: 2Gi
  limits:
    cpu: 15000m
    memory: 50Gi
persistence:
  enabled: true
  size: 10Gi
init:
  regionInit: ""
  personalInit: ""
  personalInitArgs: ""
extraEnvVars: []
kubernetes:
  enabled: true
  role: view
openshiftSCC:
  enabled: false
  scc: anyuid
vault:
  enabled: false
  token: changeme
  url: https://vault.lab.sspcloud.fr
  mount: onyxia-kv
  directory: 
  secret: ""
s3:
  enabled: true
  profiles: 
    - name : s3
      region: us-west-2
      endpoint_url: https://minio.lab.sspcloud.fr
      accessKeyId: ABC123
      secretAccessKey: XYZ456
      sessionToken: TOKEN123
      output: json
      addressing_style: path
    - name : other
      region: us-east-1
      endpoint_url: https://s3.us-east-1.amazonaws.com
      accessKeyId: OTHERKEY
      secretAccessKey: OTHERSECRET
  workingDirectoryPath: toto/
git:
  enabled: false
  name: ""
  email: ""
  cache: "0"
  token: ""
  repository: ""
  branch: ""
networking:
  user:
    enabled: false
    port: 5000
    ports:
      - 5000
discovery:
  hive: true
  mlflow: true
  metaflow: true
  chromadb: true
  milvus: true
security:
  password: changeme
  networkPolicy:
    enabled: true
    from:
      - ipBlock:
          cidr: 10.233.103.0/32
      - ipBlock:
          cidr: 10.233.111.0/32
      - ipBlock:
          cidr: 10.233.116.0/32
      - ipBlock:
          cidr: 10.233.108.0/32
nodeSelector: {}
ingress:
  enabled: false
  hostname: test-s3-config.user.lab.sspcloud.fr
  userHostname: test-s3-config.user.lab.sspcloud.fr
  ingressClassName: onyxia
  useCertManager: false
  certManagerClusterIssuer: ""
route:
  enabled: false
  hostname: test-s3-config.user.lab.sspcloud.fr
  userHostname: test-s3-config.user.lab.sspcloud.fr
repository:
  pipRepository: ""
  condaRepository: ""
startupProbe:
  failureThreshold: 60
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2
tolerations: []
userPreferences:
  darkMode: true
  language: en
  aiAssistant:
    enabled: false
    model: devstral:latest
    provider: openai
    apiBase: https://llm.lab.sspcloud.fr/api
    apiKey: ""
    useLegacyCompletionsEndpoint: false
global:
  suspend: false
proxy:
  enabled: false
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""
certificates:
  cacerts: ""
  pathToCaBundle: /usr/local/share/ca-certificates/
message:
  fr: "**NB:** ce service pourrait être supprimé après 7 jours d'utilisation en
    raison de nos règles de gestion"
  en: "**Warning:** this service may be deleted after 7 days due to our management
    policies"

