{{- if and .Values.elasticsearch.persistence.enabled (not .Values.elasticsearch.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "argilla.elasticPVCName" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.elasticsearch.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.persistence.size | quote }}
{{- if .Values.elasticsearch.persistence.storageClass }}
{{- if (eq "-" .Values.elasticsearch.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.elasticsearch.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}