apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "library-chart.fullname" . }}-cleanup-sa"
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "library-chart.fullname" . }}-cleanup-rolebinding"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-1"
subjects:
  - kind: ServiceAccount
    name: "{{ include "library-chart.fullname" . }}-cleanup-sa"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "library-chart.fullname" . }}-cleanup"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: "{{ include "library-chart.fullname" . }}-cleanup-sa"
      restartPolicy: Never
      containers:
        - name: cleanup
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
          args:
            - -c
            - |
              kubectl delete secret {{ .Values.chromadb.chromadb.auth.existingSecret | default "chromadb-auth" }} --ignore-not-found --wait=false
{{- if not .Values.savePersistentVolume }}
              kubectl delete pvc data-{{ include "chart.fullname" .Subcharts.chromadb }}-0 --ignore-not-found --wait=false
{{- end }}
