apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "library-chart.fullname" . }}-cleanup"
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: "{{ include "library-chart.fullname" . }}-cleanup-sa"
      restartPolicy: Never
      containers:
        - name: cleanup
          image: bitnami/kubectl:latest  # Uses kubectl to delete the secret
          command:
            - /bin/sh
            - -c
            - |
              kubectl delete secret {{ .Values.chromadb.chromadb.auth.existingSecret | default "chromadb-auth" }} --ignore-not-found
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "library-chart.fullname" . }}-cleanup-sa"
  labels:
    app: "{{ .Release.Name }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "library-chart.fullname" . }}-cleanup-role"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "library-chart.fullname" . }}-cleanup-rolebinding"
subjects:
  - kind: ServiceAccount
    name: "{{ include "library-chart.fullname" . }}-cleanup-sa"
roleRef:
  kind: Role
  name: "{{ include "library-chart.fullname" . }}-cleanup-role"
  apiGroup: rbac.authorization.k8s.io
