replicaCount: 1

ingress:
  enabled: true
  ingressClassName: ""
  tls: true
  hostname: "chart-example.local"
  usecertManager: false
  certManagerClusterIssuer: ""
  annotations: []

security:
  allowlist:
    enabled: false

argilla:
  image:
    pullPolicy: IfNotPresent
  env:
    ARGILLA_HOME_PATH: /var/lib/argilla
    USERNAME: argilla
    PASSWORD: changeme
    # API_KEY: argilla.apikey

persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 2Gi
  # existingClaim: ""

userPreferences:
  language: "en"
