{{- if and .Values.persistence.enabled (not .Values.persistence.argillaExistingClaim) (not (and .Values.persistence.keepPVC (lookup "v1" "PersistentVolumeClaim" .Release.Namespace (include "argilla.argillaPVCName" .)))) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "argilla.argillaPVCName" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
  {{- if .Values.persistence.keepPVC }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.argilla.storageSize | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}