apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "library-chart.fullname" . }}-hpa
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: argilla-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "library-chart.fullname" . }}
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
