apiVersion: v1
kind: Secret
metadata:
  name: {{ include "library-chart.fullname" . }}-login
type: Opaque
data:
  username: {{ .Values.security.username | b64enc | quote }}
  password: {{ .Values.security.password | b64enc | quote }}
  apikey: {{ .Values.security.password | b64enc | quote }}
