
{{- if .Values.ingress.enabled -}}
{{ if .Values.networking.user.enabled }}
{{- $fullName := include "opensearch.fullname" . -}}
{{- $svcPort := .Values.networking.user.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-user
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
  annotations:
    {{- include "opensearch.ingress.annotations" . | nindent 4 }}
spec:
  {{- if and .Values.ingress.ingressClassName (eq "true" (include "opensearch.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.userHostname | quote }}
    {{- if .Values.ingress.useCertManager }}
      secretName: tls-cert-{{ include "opensearch.fullname" . }}
    {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.userHostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $svcPort }}
{{- end }}
{{- end }}