apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "onyxia.fullname" . }}
  labels:
    app: {{ template "onyxia.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.onboarding.env }}
{{- range $key, $value := .Values.onboarding.env }}
  {{ $key }}: {{ $value | quote }}
{{- end -}}
{{- end -}}