{{- define "onyxia.onboarding.configmap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "onyxia.onboarding.name" . }}
  labels:
    app: {{ template "onyxia.onboarding.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  env.yaml: |
{{- if .Values.onboarding.env }}
{{ .Values.onboarding.env | toYaml | indent 4 }}
{{- end }}
{{- end }}