apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "library-chart.fullname" . }}-server-deployment
  labels:
    app.kubernetes.io/component: argilla-server
    app.kubernetes.io/part-of: argilla
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: argilla-server
      app.kubernetes.io/part-of: argilla
  template:
    metadata:
      labels:
        app.kubernetes.io/component: argilla-server
        app.kubernetes.io/part-of: argilla
    spec:
      initContainers:
        - name: wait-for-elasticsearch
          image: alpine/curl:latest
          command: [ "sh", "-c"]
          args:
            - |
              status_code=$(curl -s -o /dev/null -w '%{http_code}' $ELASTICSEARCH_URL)
              while [ $status_code -ne 200 ]
                do sleep 5
                status_code=$(curl -s -o /dev/null -w '%{http_code}' $ELASTICSEARCH_URL)
                echo Sleeping...
              done
              echo Elasticsearch Connected"
          env:
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch:9200"
          volumeMounts:
            - name: argilla-data
              mountPath: {{ .Values.argilla.env.ARGILLA_HOME_PATH }}
      containers:
        - name: argilla-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: ARGILLA_ELASTICSEARCH
              value: "http://elasticsearch:9200"
            - name: ARGILLA_AUTH_SECRET_KEY
              value: {{ .Values.argilla.env.PASSWORD }}
            - name: ARGILLA_HOME_PATH
              value: {{ .Values.argilla.env.ARGILLA_HOME_PATH }}
            - name: ARGILLA_ELASTICSEARCH
              value: "http://elasticsearch:9200"
            - name: ARGILLA_DATABASE_URL
              value: "postgresql+asyncpg://postgres:postgres@postgres:5432/argilla"
            - name: ARGILLA_REDIS_URL
              value: "redis://redis:6379/0"
            - name: USERNAME
              value: {{ .Values.argilla.env.USERNAME }}
            - name: PASSWORD
              value: {{ .Values.argilla.env.PASSWORD }}
            - name: API_KEY
              value: {{ .Values.argilla.env.API_KEY }}
          ports:
            - containerPort: 6900
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 100m
      volumes:
        - name: argilla-data
          persistentVolumeClaim:
            claimName: argilla-pvc
