security:
  password: MyStr0ngP@ssword

opensearch: 
  ingress:
    enabled: true
    ingressClassName: ""
    hosts: 
      - example.user.lab.sspcloud.fr
    tls: 
      - hosts:
        - example.user.lab.sspcloud.fr
  networkPolicy:
    create: true
    http:
      enabled: false
  securityConfig:
    enabled: true
  envFrom:
  - secretRef: 
      name: env-secret

opensearch-dashboards:
  ingress: 
    enabled: true
    ingressClassName: ""
    annotations: {}
    labels: {}
    hosts:
      - host: example-dashboards.user.lab.sspcloud.fr
        paths:
          - path: /
            backend:
              serviceName: ""
              servicePort: ""
    tls:
      - hosts:
        - example-dashboards.user.lab.sspcloud.fr
  serviceAccount:
    create: false 
  rbac:
    create: false

